name: node-app
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Deploying  
              run: echo "Deploying..."  
    docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag sammakaorz/node-app          
            